import {baseProfile,rank,simulate,institutionAblation} from './engine.js';
const $=s=>document.querySelector(s),escapeHtml=v=>String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const skillOptions=['python','react','statistics','git','testing','api','database','cloud'];
const experienceOptions=[['leadership','Leadership'],['solo-project','Solo project'],['team','Team project'],['backend','Backend work'],['research','Research'],['opensource','Open source'],['deployment','Deployment']];
const sample={...structuredClone(baseProfile),major:'Statistics and Data Science',education:'transfer student',season:'Summer 2027',company:'Large technology company',target:'Software engineering'};
let profile;try{profile=JSON.parse(localStorage.getItem('internship-pathway-profile'))||sample}catch{profile=sample}
let model='hybrid',current=[],selectedId='',pendingScenario=null;
const info={
 evidence:['Recommendation evidence','Scores combine the exact skills already in your profile, the gaps each experience addresses, and descriptive pathway links. Click any ranked recommendation to inspect its feature-grounded explanation.'],
 experiments:['Model comparison','The four selectable models intentionally produce different rankings. Rules prioritize missing experience, content emphasizes skill overlap, graph scoring emphasizes observed transitions, and hybrid combines all three.'],
 model:['Model card','This demonstration uses a small synthetic opportunity set. It is designed to make scoring inspectable, not to estimate a real hiring probability. Every explanation is built from scorer features.'],
 responsible:['Responsible use','This tool never predicts whether someone will be hired. It excludes protected attributes, names, and photos. Institution is optional and its sensitivity is displayed through an ablation. Recommendations should be treated as ideas to investigate, not decisions.']
};
function persist(){localStorage.setItem('internship-pathway-profile',JSON.stringify(profile))}
function render(){current=rank(profile,model);selectedId=current.some(x=>x.id===selectedId)?selectedId:current[0].id;const features=[...profile.skills,...profile.experiences];$('#targetLine').textContent=`Target: ${profile.season} · ${profile.target} · ${profile.company}`;$('#profileTitle').textContent=`${profile.major} · ${profile.education}`;$('#profileFeatures').textContent=features.map(titleCase).join(' · ');$('#currentEvidence').textContent=profile.experiences.length?profile.experiences.map(titleCase).join(' + '):'Skills without formal experience';$('#targetEvidence').textContent=`Evidence for ${profile.target}`;$('#gapText').textContent=current[0].why[0].replace('Addresses ','');const completeness=Math.min(100,Math.round((profile.skills.length/5*.6+profile.experiences.length/3*.4)*100));$('#profileCompletion').textContent=`Profile ${completeness}% complete`;$('#confidenceText').textContent=completeness>=80?'High':completeness>=50?'Moderate':'Limited';$('#recommendations').innerHTML=current.map((r,i)=>`<button class="recommendation ${r.id===selectedId?'selected':''}" data-id="${r.id}"><span class="rank">0${i+1}</span><div><h3>${escapeHtml(r.title)}</h3><p>${escapeHtml(r.type)} · ${escapeHtml(r.next)}</p></div><span class="score">${r.score}</span></button>`).join('');document.querySelectorAll('.recommendation').forEach(el=>el.onclick=()=>select(el.dataset.id));select(selectedId);renderAblation()}
function select(id){selectedId=id;document.querySelectorAll('.recommendation').forEach(x=>x.classList.toggle('selected',x.dataset.id===id));const r=current.find(x=>x.id===id);if(!r)return;$('#bridgeTitle').textContent=r.title;$('#bridgeScore').textContent=`Pathway score ${r.score}/100`;$('#why').innerHTML=r.why.map(x=>`<li>${escapeHtml(x)}</li>`).join('')}
function renderAblation(){const ab=institutionAblation(profile);$('#ablation').innerHTML=ab.scores.map(x=>`<div><span>${titleCase(x.variant)}</span><b>${x.topScore}</b></div>`).join('')+`<div><span>Maximum sensitivity</span><b>${ab.sensitivity} pts</b></div>`}
function openProfile(){$('#majorInput').value=profile.major;$('#educationInput').value=profile.education;$('#roleInput').value=profile.target;$('#companyInput').value=profile.company;$('#seasonInput').value=profile.season;$('#customSkillInput').value='';$('#skillChecks').innerHTML=skillOptions.map(s=>`<label><input type="checkbox" value="${s}" ${profile.skills.includes(s)?'checked':''}>${titleCase(s)}</label>`).join('');$('#experienceChecks').innerHTML=experienceOptions.map(([v,l])=>`<label><input type="checkbox" value="${v}" ${profile.experiences.includes(v)?'checked':''}>${l}</label>`).join('');$('#profileDialog').showModal()}
function saveProfile(){const checkedSkills=[...document.querySelectorAll('#skillChecks input:checked')].map(x=>x.value),custom=$('#customSkillInput').value.split(',').map(x=>x.trim().toLowerCase()).filter(Boolean),experiences=[...document.querySelectorAll('#experienceChecks input:checked')].map(x=>x.value);profile={...profile,major:$('#majorInput').value.trim()||'Undeclared',education:$('#educationInput').value,target:$('#roleInput').value,company:$('#companyInput').value,season:$('#seasonInput').value.trim()||'Next season',skills:[...new Set([...checkedSkills,...custom])],experiences};persist();render();$('#profileDialog').close();toast('Profile saved and recommendations recalculated.')}
function runScenario(){const [kind,value]=$('#scenario').value.split(':'),x=simulate(profile,{kind,value},model),best=x.deltas.slice().sort((a,b)=>b.delta-a.delta)[0],item=x.after.find(a=>a.id===best.id);pendingScenario={kind,value};$('#scenarioResult').innerHTML=`<small>BEST PROJECTED CHANGE</small><strong>${best.delta>=0?'+':''}${best.delta} points</strong><span>${escapeHtml(item.title)} · rank #${x.after.findIndex(a=>a.id===best.id)+1}</span><button id="applyScenarioBtn">Apply to profile</button>`;$('#applyScenarioBtn').onclick=applyScenario;toast('Comparison complete; your saved profile is unchanged.')}
function applyScenario(){if(!pendingScenario)return;const list=pendingScenario.kind==='skill'?profile.skills:profile.experiences;if(!list.includes(pendingScenario.value))list.push(pendingScenario.value);persist();render();$('#scenarioResult').innerHTML=`<small>PROFILE UPDATED</small><strong>Applied</strong><span>${titleCase(pendingScenario.value)} is now part of your profile.</span>`;pendingScenario=null;toast('Scenario applied and rankings updated.')}
function showInfo(key){const [title,body]=info[key];$('#infoKicker').textContent=key.toUpperCase();$('#infoTitle').textContent=title;$('#infoBody').innerHTML=`<p>${escapeHtml(body)}</p>`;$('#infoDialog').showModal()}
function titleCase(v){return String(v).replaceAll('-',' ').replace(/\b\w/g,c=>c.toUpperCase())}
function toast(m){const e=$('#toast');e.textContent=m;e.classList.add('show');clearTimeout(window.pathToast);window.pathToast=setTimeout(()=>e.classList.remove('show'),2800)}
$('#model').onchange=e=>{model=e.target.value;render();toast(`${e.target.options[e.target.selectedIndex].text} applied.`)};$('#simulateBtn').onclick=runScenario;$('#editBtn').onclick=openProfile;$('#saveProfileBtn').onclick=saveProfile;$('#resetProfileBtn').onclick=()=>{profile=structuredClone(sample);persist();openProfile();toast('Sample profile restored.')};document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>document.getElementById(b.dataset.close).close());document.querySelectorAll('[data-info]').forEach(b=>b.onclick=()=>showInfo(b.dataset.info));document.querySelectorAll('aside nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('aside nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');const a=b.dataset.action;if(a==='profile')openProfile();else if(a==='pathway'||a==='dashboard')document.getElementById(a==='pathway'?'pathwaySection':'dashboard').scrollIntoView({behavior:'smooth'});else if(a==='scenarios')$('#scenarioSection').scrollIntoView({behavior:'smooth'});else showInfo(a)});
render();
