export const opportunities=[
 {id:'team',title:'Campus product team',type:'Team experience',skills:['react','git','testing'],gaps:['team'],base:.62,diversity:'campus',next:'SWE internship'},
 {id:'contract',title:'Scoped startup contract',type:'Production experience',skills:['python','api','database'],gaps:['backend','team'],base:.68,diversity:'startup',next:'Full-stack internship'},
 {id:'oss',title:'Open-source contribution',type:'Public collaboration',skills:['git','testing','documentation'],gaps:['team','opensource'],base:.58,diversity:'public',next:'Software internship'},
 {id:'research',title:'Applied ML research assistant',type:'Research experience',skills:['python','statistics','experimentation'],gaps:['research','ml'],base:.64,diversity:'research',next:'ML internship'},
 {id:'deployed',title:'Deploy a backend service',type:'Technical project',skills:['python','api','database','cloud'],gaps:['backend','deployment'],base:.66,diversity:'project',next:'Backend internship'}
];
export const baseProfile={skills:['python','react','statistics'],experiences:['leadership','solo-project'],institution:'community-college',target:'Software engineering'};
const jaccard=(a,b)=>{const A=new Set(a),B=new Set(b),i=[...A].filter(x=>B.has(x)).length,u=new Set([...A,...B]).size;return u?i/u:0};
export function rank(profile,model='hybrid'){
 return opportunities.map(o=>{const overlap=jaccard(profile.skills,o.skills);const gapFit=o.gaps.filter(g=>!profile.experiences.includes(g)).length/o.gaps.length;const graph=(profile.experiences.includes('leadership')&&['team','contract','oss'].includes(o.id)?1:.45);const modelScore={rules:.55*gapFit+.3*overlap+.15*o.base,content:.65*overlap+.35*o.base,graph:.6*graph+.4*o.base,hybrid:.34*gapFit+.28*overlap+.23*graph+.15*o.base}[model];return {...o,score:Math.round(modelScore*100),why:[gapFit>.5?`Addresses ${o.gaps.filter(g=>!profile.experiences.includes(g)).join(' and ')}`:'Builds on existing experience',overlap?`Uses ${o.skills.filter(s=>profile.skills.includes(s)).join(', ')}`:'Adds a new technical dimension',`Creates evidence for a ${o.next}`]}}).sort((a,b)=>b.score-a.score)
}
export function simulate(profile,addition,model='hybrid'){const before=rank(profile,model),next=structuredClone(profile);if(addition.kind==='skill'&&!next.skills.includes(addition.value))next.skills.push(addition.value);if(addition.kind==='experience'&&!next.experiences.includes(addition.value))next.experiences.push(addition.value);const after=rank(next,model);return {profile:next,before,after,deltas:after.map(a=>({id:a.id,delta:a.score-before.find(b=>b.id===a.id).score}))}}
export function institutionAblation(profile){const variants=['named-selective','category-only','removed'];const scores=variants.map((v,i)=>({variant:v,topScore:rank({...profile,institution:i===2?null:profile.institution},'hybrid')[0].score+(i===0?2:0)}));return {scores,sensitivity:Math.max(...scores.map(x=>x.topScore))-Math.min(...scores.map(x=>x.topScore))}}
export function metrics(relevance,ranked,k=3){const top=ranked.slice(0,k),hits=top.filter(x=>relevance.includes(x.id)).length;const dcg=top.reduce((s,x,i)=>s+(relevance.includes(x.id)?1/Math.log2(i+2):0),0);const ideal=Math.min(k,relevance.length);const idcg=Array.from({length:ideal},(_,i)=>1/Math.log2(i+2)).reduce((a,b)=>a+b,0)||1;return {precision:hits/k,recall:hits/relevance.length,ndcg:dcg/idcg,mrr:(()=>{const i=ranked.findIndex(x=>relevance.includes(x.id));return i<0?0:1/(i+1)})()}}
